# Generated by Django 4.2.5 on 2023-10-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upscaler_django_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='bilinear_image',
            field=models.ImageField(blank=True, null=True, upload_to='upscaled_images/bilinear/'),
        ),
        migrations.AddField(
            model_name='image',
            name='dwsr_image',
            field=models.ImageField(blank=True, null=True, upload_to='upscaled_images/dwsr/'),
        ),
        migrations.AddField(
            model_name='image',
            name='esrgan_image',
            field=models.ImageField(blank=True, null=True, upload_to='upscaled_images/esrgan/'),
        ),
    ]
