# Generated by Django 4.2.5 on 2023-10-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upscaler_django_backend', '0002_image_bilinear_image_image_dwsr_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dominant_colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
