# Generated by Django 4.2.5 on 2023-12-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upscaler_django_backend', '0003_image_dominant_colors_image_original_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='bilinear_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='dwsr_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='esrgan_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
